name: Revertir Sesion
description: Solicita la cancelación de una sesión
title: "[Soporte]: "
labels: ["revert", "needs triage"]
assignees: ["cjaviersaldana"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por contactarnos para solicitar la cancelación de la sesión!
  - type: input
    id: cedula
    attributes:
      label: Número de cédula
      description: Ingresa solo números para el número de cédula
      placeholder: "Ejemplo: 1234567890"
    validations:
      required: true